version: '3.3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  api:
    depends_on:
      - db
    build: .
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_HOST=postgres://postgres:postgres@postgres:5432?sslmode=disable
    logging:
      options:
        max-size: "2m"
        max-file: "3"
    # stdin_open: true
    # tty: true
    stdin_open: true
    tty: true
volumes:
  db:
    driver: local